### ISSUE TITLE
Unable to install graphics on a fresh opam installation on Mac OS 10.14.6

### ISSUE THREAD

**Issue by Poirriez** [ocaml/graphics#18] opened 2019-12-09 15:13 UTC
Here is the output of `opam install graphics`
```
$ opam install graphics
The following actions will be performed:
  ∗ install   conf-pkg-config 1.1   [required by conf-libX11]
  ∗ install   conf-libX11     1     [required by graphics]
  ∗ install   graphics        5.0.0
  ↻ recompile ocamlfind       1.8.1 [uses graphics]
===== ∗ 3   ↻ 1 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ocamlfind.1.8.1] found in cache
[graphics.5.0.0] downloaded from https://github.com/ocaml/graphics/releases/download/5.0.0/graphics-5.0.0.tbz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
⊘ removed   ocamlfind.1.8.1
∗ installed conf-pkg-config.1.1
∗ installed conf-libX11.1
[ERROR] The compilation of graphics failed at
        "/Users/vpoirrie/.opam/opam-init/hooks/sandbox.sh build dune build -p
        graphics -j 3 @install".

#=== ERROR while compiling graphics.5.0.0 =====================================#
# context     2.0.4 | macos/x86_64 | ocaml-system.4.09.0 | https://opam.ocaml.org#bd644e85
# path        ~/_opam/.opam-switch/build/graphics.5.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p graphics -j 3 @install
# exit-code   1
# env-file    ~/.opam/log/graphics-12083-48c407.env
# output-file ~/.opam/log/graphics-12083-48c407.out
### output ###
# [...]
# In file included from src/unix/text.c:16:
# src/unix/libgraph.h:17:10: fatal error: 'X11/Xlib.h' file not found
# #include <X11/Xlib.h>
#          ^~~~~~~~~~~~
# 1 error generated.
#       ocamlc src/subwindow.o (exit 2)
# (cd _build/default/src && /usr/local/bin/ocamlc.opt -g -ccopt -O2 -ccopt -fno-strict-aliasing -ccopt -fwrapv -ccopt -g -o subwindow.o subwindow.c)
# In file included from src/unix/subwindow.c:16:
# src/unix/libgraph.h:17:10: fatal error: 'X11/Xlib.h' file not found
# #include <X11/Xlib.h>
#          ^~~~~~~~~~~~
# 1 error generated.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build graphics 5.0.0
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ⊘ remove  ocamlfind       1.8.1
│ ∗ install conf-libX11     1
│ ∗ install conf-pkg-config 1.1
└─ 
```

**Comment by nojb** [comment] 2019-12-09 15:16
Duplicate of #16 ?

**Comment by nojb** [comment] 2019-12-09 15:18
I think this bug has been correcte in #17, but the fix has not yet been released to `opam`. In the meantime you can try doing
```
export LIBRARY_PATH=/opt/X11/lib
```
before `opam install graphics`.

**Comment by dra27** [comment] 2020-12-24 12:43
This was fixed in graphics 5.1.0

**Closed by dra27** 2020-12-24 12:43 UTC

**Comment by zhangtravis** [comment] 2021-05-21 18:05
I have the same problem as mentioned, and I tried running `export LIBRARY_PATH=/opt/X11/lib` before running `opam install graphics`, and that does not seem to work.

**Comment by dra27** [comment] 2021-05-21 19:48
It's hopefully not the same problem, because you shouldn't be trying to install version 5.0.0 of the library! Please could you post the error you're getting - in particular, the export shown above was a workaround - has `opam install conf-libX11` succeeded?

**Comment by zhangtravis** [comment] 2021-05-21 19:58
Hi @dra27, here is the error I am getting:
